<!DOCTYPE html>
<html lang="pl">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>3cityevent</title>
    <link rel="canonical" href="#">
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <#-- Custom styles for this template -->
    <link href="css/main.css" rel="stylesheet">
</head>
<body>
<#include "navbar.ftlh">
<div class="container-fluid">
    <div class="row text-center">
        <#include "card-of-event.ftlh">
        </div>
    </div>

<header class="jumbotron my-4 text-center">
    <h1 class="display-3 font-weight-bold">3CITYEVENT</h1>
    <p class="lead">Witaj w miejscu, gdzie zgromadzone są wydarzenia kulturalne w Trójmiescie i okolicy.
        </br>Szukaj, znajdź, rezerwuj i baw się dobrze!</p>
</header>

</body>